<?xml version="1.0" encoding="utf-8"?><Database Name="Stefans" Class="DBCoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=srv63bits;Initial Catalog=Stefans;Persist Security Info=True;User ID=sa" SettingsObjectName="DB.Properties.Settings" SettingsPropertyName="StefansConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.UM_tsp_Users" Method="UM_tsp_Users">
    <Parameter Name="iud" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address1" Parameter="address1" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Address2" Parameter="address2" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="StateID" Parameter="stateID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Zip" Parameter="zip" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.IsEmailUnique" Method="IsEmailUnique" IsComposable="true">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="dbo.List_Dictionaries" Method="List_Dictionaries" IsComposable="true">
    <Parameter Name="Level" Parameter="level" Type="System.Int32" DbType="Int" />
    <Parameter Name="DictionaryCode" Parameter="dictionaryCode" Type="System.Int32" DbType="Int" />
    <Parameter Name="ShowInvisibleItems" Parameter="showInvisibleItems" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="List_DictionariesResult">
      <Column Name="RowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DictionaryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="uid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Caption" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Caption1" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CodeVal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Level]" Member="Level" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Hierarchy" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="StringCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DictionaryCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DefVal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SortVal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DecimalVal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CRTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.UM_GetSingle_User" Method="UM_GetSingle_User" IsComposable="true">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(500)" />
    <Return Type="System.Xml.Linq.XElement" />
  </Function>
  <Function Name="dbo.tx_Products" Method="tx_Products">
    <Parameter Name="iud" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="x" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="out" Type="System.Xml.Linq.XElement" DbType="Xml" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.tsp_Products" Method="tsp_Products">
    <Parameter Name="iud" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Caption" Parameter="caption" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Instructions" Parameter="instructions" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.tsp_ProductTestimonials" Method="tsp_ProductTestimonials">
    <Parameter Name="iud" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="RecordID" Parameter="recordID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(2000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetSingle_ProductTestimonial" Method="GetSingle_ProductTestimonial" IsComposable="true">
    <Parameter Name="RecordID" Parameter="recordID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Xml.Linq.XElement" />
  </Function>
  <Function Name="dbo.List_ProductTestimonials" Method="List_ProductTestimonials" IsComposable="true">
    <ElementType Name="List_ProductTestimonialsResult">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="CRTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ProductCaption" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.List_Products" Method="List_Products" IsComposable="true">
    <ElementType Name="List_ProductsResult">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Caption" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Instructions" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IsFeature" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CRTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSingle_Product" Method="GetSingle_Product" IsComposable="true">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="IncludeTestimonials" Parameter="includeTestimonials" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Xml.Linq.XElement" />
  </Function>
  <Function Name="dbo.tsp_Favourites" Method="tsp_Favourites">
    <Parameter Name="iud" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="FavouriteID" Parameter="favouriteID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.List_Favourites" Method="List_Favourites" IsComposable="true">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="List_FavouritesResult">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Caption" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.tsp_CartItems" Method="tsp_CartItems">
    <Parameter Name="iud" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="CartItemID" Parameter="cartItemID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.List_CartItems" Method="List_CartItems" IsComposable="true">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="List_CartItemsResult">
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Caption" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.tsp_ADNTransactions" Method="tsp_ADNTransactions">
    <Parameter Name="iud" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="RecordID" Parameter="recordID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="OrderID" Parameter="orderID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ADNTransactionID" Parameter="aDNTransactionID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="RequestStr" Parameter="requestStr" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ResponseStr" Parameter="responseStr" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.tx_Orders" Method="tx_Orders">
    <Parameter Name="iud" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="x" Type="System.Xml.Linq.XElement" DbType="Xml" />
    <Parameter Name="out" Type="System.Xml.Linq.XElement" DbType="Xml" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>