<?xml version="1.0" encoding="utf-8"?><Database Name="Stefans" Class="DBUMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=srv63bits;Initial Catalog=Stefans;Persist Security Info=True;User ID=sa" SettingsObjectName="DB.Properties.Settings" SettingsPropertyName="StefansConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.UM_tsp_Users" Method="UM_tsp_Users">
    <Parameter Name="iud" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address1" Parameter="address1" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Address2" Parameter="address2" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="StateID" Parameter="stateID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Zip" Parameter="zip" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
</Database>