//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is incorrect!.
        /// </summary>
        public static string ErrorADNCardNumber {
            get {
                return ResourceManager.GetString("ErrorADNCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCV is incorrect!.
        /// </summary>
        public static string ErrorADNCCV {
            get {
                return ResourceManager.GetString("ErrorADNCCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exparation date is incorrect!.
        /// </summary>
        public static string ErrorADNExpDate {
            get {
                return ResourceManager.GetString("ErrorADNExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email is already registered!.
        /// </summary>
        public static string ErrorEmailDuplication {
            get {
                return ResourceManager.GetString("ErrorEmailDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid extensions area: {0}!.
        /// </summary>
        public static string ErrorFileExtension {
            get {
                return ResourceManager.GetString("ErrorFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of the field {0} is {1}!.
        /// </summary>
        public static string ErrorMaxLength {
            get {
                return ResourceManager.GetString("ErrorMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be numeric!.
        /// </summary>
        public static string ErrorNumeric {
            get {
                return ResourceManager.GetString("ErrorNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original password is incorrect!.
        /// </summary>
        public static string ErrorOriginalPassword {
            get {
                return ResourceManager.GetString("ErrorOriginalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match!.
        /// </summary>
        public static string ErrorPasswordMismatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was unsuccessful. Sorry for the inconvenience..
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was successful..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
